1. Create a NumPy array of integers from 1 to 10.

In [ ]:
import numpy as np
A=np.arange(1,11)

In [ ]:
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2.Create a 2x3 NumPy array filled with zeros

In [ ]:
A=np.zeros((2,3))
A

array([[0., 0., 0.],
       [0., 0., 0.]])

3.Create a NumPy array of even numbers from 2 to 20.

In [ ]:
B=np.arange(2,21,2)
B

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4.Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division between the two arrays.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr=arr1+arr2
arr3=arr2-arr1
arr4=arr1*arr2
arr5=arr1/arr2
print(arr)
print(arr3)
print(arr4)
print(arr5)



[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]


6. Reshape a 1D NumPy array of 12 random elements into a 2D array with a
shape of (3, 4).

In [ ]:
ar=np.array([15,16,12,14,11,10,8,9,17,20,21,22])
ar1=ar.reshape(3,4)
ar1

array([[15, 16, 12, 14],
       [11, 10,  8,  9],
       [17, 20, 21, 22]])

7.Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in
the array using NumPy functions.

In [107]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr1=arr*arr
arr1

array([ 1,  4,  9, 16, 25])

8.Create a 5x5 identity matrix using NumPy.

In [ ]:
arr=np.eye(5,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9.Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and
b = np.array([4, 5, 6]).

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [8]:
a.dot(b)

32

10.Find the index of the maximum value and the index of the minimum value
in a NumPy array.

In [ ]:
a=np.array([10,12,20,16,71,54,9,11])


In [35]:
a.argmax()



4

In [36]:
a.argmin()

6

11.Concatenate two random NumPy arrays horizontally and vertically

In [46]:
a=np.array([[1,2,3,],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b=np.array([[9,8,7],[6,5,4]])
b

array([[9, 8, 7],
       [6, 5, 4]])

In [48]:
c=np.concatenate((a,b),axis=0)
c

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [49]:
d=np.concatenate((a,b),axis=1)
d

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4]])

12.Given a 2D NumPy array, calculate the sum of each row and each column
separately.


In [50]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
n=np.sum(a,axis=0)
n

array([12, 15, 18])

In [64]:
n1=np.sum(a,axis=1)
n1

array([ 6, 15, 24])

13.Find the common elements between two NumPy arrays

In [70]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([1,3,6,4,11,10,5,9,15])
for i in a:
  if i in b:
    print(i)





1
3
4
5
6
9


14.Replace all negative values in a NumPy array with zeros.

In [74]:
a=np.array([1,-2,3,-4,5,-6,7,-8,9])
a[a<0]=0
print(a)


[1 0 3 0 5 0 7 0 9]


15.Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.

In [108]:
a=np.random.randint(1,101,10)
a

array([43, 47,  4, 24, 21, 18, 20, 30, 50, 82])

In [109]:
a.sort()
a

array([ 4, 18, 20, 21, 24, 30, 43, 47, 50, 82])

16.Calculate the element-wise absolute difference between two NumPy
arrays.

In [110]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([1,3,6,4,11,10,5,9,15])
s=np.abs(a-b)
s

array([0, 1, 3, 0, 6, 4, 2, 1, 6])


17.Given a 2D NumPy array, extract the first row and the last column.

In [81]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a[0]

array([1, 2, 3])

In [83]:
a[0:3,(2)]

array([3, 6, 9])

18.Slice a 1D NumPy array to get every other element

In [90]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

19.Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [91]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
a[1:3,(1,2)]

array([[ 6,  7],
       [10, 11]])

20.Reverse a 1D NumPy array using slicing


In [96]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])


5.Compute the mean, median, and standard deviation of a NumPy array
containing 100 random numbers.

In [111]:
a=np.random.rand(100)
a

array([0.69517316, 0.05291889, 0.96258441, 0.65588637, 0.93843568,
       0.32543161, 0.71272393, 0.40192822, 0.88328939, 0.13603042,
       0.78156178, 0.02012698, 0.35248964, 0.93830251, 0.0489188 ,
       0.98667265, 0.64270013, 0.28616265, 0.59069892, 0.30001715,
       0.42598147, 0.65837622, 0.65044854, 0.39723362, 0.26176703,
       0.13642573, 0.03665745, 0.93096271, 0.88101682, 0.54507603,
       0.78864665, 0.55737252, 0.51806983, 0.88405695, 0.19804241,
       0.05482426, 0.10636677, 0.91281991, 0.15918687, 0.17710588,
       0.29146407, 0.67559949, 0.35032701, 0.45152022, 0.83856412,
       0.414853  , 0.74007427, 0.2633341 , 0.31567905, 0.2604351 ,
       0.76714307, 0.69427791, 0.0188461 , 0.79625948, 0.74979834,
       0.72212603, 0.11791513, 0.83752145, 0.69945936, 0.27563554,
       0.05312973, 0.93901741, 0.34726946, 0.64035728, 0.5920778 ,
       0.5816183 , 0.14178265, 0.43001283, 0.00785733, 0.18447883,
       0.56080545, 0.02308499, 0.21129249, 0.68785621, 0.00543

In [112]:
a.mean()

0.49628820603873014

In [113]:
import statistics
statistics.median(a)

0.503582668855767

In [114]:
a.std()

0.29796200620774305